//! Microsoft app logo output specification.
//!
//! This module intentionally models only the small, practical set requested
//! for v1.26.0. It is not a full Windows packaging asset matrix.

/// One Microsoft app logo output item.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MicrosoftAppLogoSpec {
    pub file_name: &'static str,
    pub width: u32,
    pub height: u32,
}

/// Minimal Microsoft app logo set generated by Logolig v1.26.0.
pub const MICROSOFT_APP_LOGOS: [MicrosoftAppLogoSpec; 4] = [
    MicrosoftAppLogoSpec {
        file_name: "StoreLogo.png",
        width: 50,
        height: 50,
    },
    MicrosoftAppLogoSpec {
        file_name: "Square44x44Logo.png",
        width: 44,
        height: 44,
    },
    MicrosoftAppLogoSpec {
        file_name: "Square150x150Logo.png",
        width: 150,
        height: 150,
    },
    MicrosoftAppLogoSpec {
        file_name: "Wide310x150Logo.png",
        width: 310,
        height: 150,
    },
];
