[package]
name = "logolig-i18n"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Translations for logolig. Translates `logolig_core::MessageKey` to localized strings."

[dependencies]
logolig-core.workspace = true
serde.workspace = true
toml.workspace = true
sys-locale.workspace = true

[lints]
workspace = true
